# Generated by Django 3.0.4 on 2020-09-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='content',
            new_name='Symptoms',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='expiry_date',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='location',
            new_name='previous_history',
        ),
    ]
