# Generated by Django 3.0.4 on 2020-09-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patients_disatisfy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='id',
        ),
        migrations.AddField(
            model_name='patients',
            name='Book_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='Current',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patients',
            name='UID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
