# Generated by Django 3.0.4 on 2020-09-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200919_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Current',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Deduct',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Disatisfy',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
