# Generated by Django 3.0.4 on 2020-09-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200919_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='Copay',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='Deduct',
        ),
    ]
