# Generated by Django 3.0.4 on 2020-09-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_patients_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
