# Generated by Django 3.1.1 on 2020-09-23 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_patients_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ins_Policy',
            fields=[
                ('plan', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming_patients',
            fields=[
                ('UID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Scheduled_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('UID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Street', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=150)),
                ('State', models.CharField(max_length=150)),
                ('Pin', models.IntegerField()),
                ('Insurance_policy_plan', models.CharField(default='', max_length=30)),
                ('out_of_pocket_limit', models.IntegerField()),
                ('Limit_left', models.IntegerField()),
                ('Copay', models.IntegerField()),
                ('Coinsurance', models.FloatField()),
                ('Deductible', models.IntegerField()),
                ('Deduct_Paid', models.IntegerField()),
                ('Current', models.IntegerField(null=True)),
                ('Disatisfy', models.CharField(default='', max_length=100, null=True)),
                ('flagged', models.BooleanField(default=False)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
