# Generated by Django 3.1.1 on 2020-09-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ins_policy_patient_upcoming_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Current',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Disatisfy',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
