# Generated by Django 3.1.1 on 2020-09-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200923_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_patient',
            fields=[
                ('UID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Scheduled_date', models.DateField()),
                ('Payment_by_payer', models.FloatField()),
                ('Payment_by_dependant', models.FloatField()),
            ],
        ),
    ]
