# Generated by Django 3.1.1 on 2020-09-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_upcoming_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scheduled_date', models.DateField()),
                ('Payment_by_payer', models.FloatField()),
                ('Payment_by_dependant', models.FloatField()),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
