# Generated by Django 3.1.1 on 2020-09-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_upcoming'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
