# Generated by Django 3.1.1 on 2020-09-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_patients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upcoming_patient',
        ),
        migrations.DeleteModel(
            name='Upcoming_patients',
        ),
    ]
