# Generated by Django 3.1.1 on 2020-09-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200926_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ins_Policy',
        ),
    ]
